config/routes.rb
Tweb::Application.routes.draw do

  resources :prefectures

  resources :nomos

  match  "/search" => "hits#search"
  match  "/myhits" => "hits#myhits"
  match  "/mybids" => "bids#mybids"
  resources :hits do
  resources :bids
end

resources :bids do
  put :accept, :on => :member
  put :inactive, :on => :member
end

get 'bids/accept'

  resources :categories
  devise_for :users

  resources :hits

  get "home/index"

namespace 'chargify' do
 match '/hooks' => "hooks#dispatch_handler", :via => "post"
 end

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post

   root :to => 'home#index'

end

app/models/bid.rb
# encoding: utf-8

class Bid < ActiveRecord::Base
     paginates_per 10
validates :size, :pm, :presence => true
belongs_to :user
belongs_to :hit





end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
before_filter :authenticate_user!

  # GET /bids
  # GET /bids.json



  def index
    @bids = Bid.where("hit_id = ?", params[:hit_id]).page(params[:page])
    @userbids = @bids.count
    @hit = Hit.find(params[:hit_id])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bids }
    end
  end

def mybids
    @bids = Bid.where("user_id = ?", current_user.id).page(params[:page])
    @userbids = @bids.count
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hits }
    end
  end


  # GET /bids/1
  # GET /bids/1.json
  def show
    @bid = Bid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/new
  # GET /bids/new.json
  def new

@bid = Bid.new(:hit_id => params[:hit_id])
@mobids = @bid.hit.bids.average('size')
@currentbids = @bid.hit.bids
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/1/edit
  def edit
    @bid = Bid.find(params[:id])
  end

  # POST /bids
  # POST /bids.json
  def create
    @bid = Bid.new(params[:bid])

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render json: @bid, status: :created, location: @bid }
      else
        format.html { render action: "new" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bids/1
  # PUT /bids/1.json
  def update
    @bid = Bid.find(params[:id])

    respond_to do |format|
      if @bid.update_attributes(params[:bid])
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
  def destroy
    @bid = Bid.find(params[:id])
    @bid.destroy
    flash[:notice] = "Successfully destroyed post."
    respond_to do |format|
      format.html { redirect_to "/mybids" }
      format.json { head :no_content }
    end
  end


 def inactive
    @bid = Bid.find(params[:id])
    @bid.update_attribute(:active, false)
end

  def accept
    @bid = Bid.find(params[:id])
    @hit = @bid.hit
    @hit.update_attribute(:haveaccept, true)
    @bid.update_attribute(:accept, true)
    @bid.hit.bids.each do |rejected_bid|
      rejected_bid.update_attribute(:active, false) unless rejected_bid == @bid   # destroys all be the accepted bid
    end

    flash[:notice] = "Successfully destroyed post."
    respond_to do |format|
      format.html { redirect_to "/mybids" }
      format.json { head :no_content }
    end
  end

end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<p>Προσφορά για την αγγελία:<h2><%= @bid.hit.subject  %></h2>
</p>


<%= simple_form_for @bid , :html => { :class => 'form-horizontal' } do |f| %>
  <fieldset>
    <legend>Λεπτομέριες προσφοράς </legend>

    <div class="control-group">
      <%= f.label :Προσφορά, :class => 'control-label'  %>
      <div class="controls">
        <%= f.number_field :size, :class => 'number_field', :placeholder => @mobids%>
<p class="help-block">Hit! Ο μέσος όρος των προσφορών που έχουν ήδη γίνει εμφανίζεται πριν κάνετε την προσφορά.</p>
      </div>
    </div>

    <div class="control-group">
      <%= f.label :Μήνυμα, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :pm, :class => 'text_field' %>
<p class="help-block">Μαζί με την προσφορά καλό θα ήταν να στείλετε και ένα μήνυμα προς τον ενδιαφερόμενο (π.χ. Επαγγελματική προϋπηρεσία, πλάνο εργασίας κτλ.).</p>
      </div>
    </div>




    <%= f.hidden_field :hit_id, :value => @bid.hit_id %>
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="form-actions">
      <%= f.submit 'Καταχώρηση προσφοράς', :class => 'btn btn-primary' %>
      <%= link_to 'Άκυρο', "/mybids", :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/bids/edit.html.erb
<%= render :partial => 'form' %>

app/views/bids/index.html.erb
<% if @bids.count  == 0 %>
<h2>Προσφορές για την αγγελία:</h2><h3><%= @hit.subject%></h3>
</br>
<h3>Δεν υπάρχουν ακόμη προσφορές</h3>
</br>
<%if @hit.user_id == current_user.id%>
<p></br></br></br></br></p>
<%else%>
<p>Για να κάνετε μια προσφορά πατήστε <%= link_to 'εδώ', new_hit_bid_path(@hit), :class => 'btn btn-info' %> και καταθέστε μια προσφορά για την αγγελία!</p>
</br>
</br>
<%end%>
<%else%>




<h2>Προσφορές για την αγγελία:</h2><h3><%= @hit.subject%></h3>
</br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th>Προσφορά</th>
      <th>Μήνυμα</th>
      <th>Κατατέθηκε</th>
      <th>Χρήστης</th>
<%if current_user.id == @hit.user_id %>
      <th>Ενέργειες</th>
<%end%>

    </tr>
  </thead>
  <tbody>
    <% @bids.each do |bid| %>
      <tr>
        <td><%= bid.id %></td>
        <td><%= link_to bid.size, bid_path(bid) %></td>
        <td><%= bid.pm %></td>
        <td><%= bid.created_at %></td>
        <td><%= bid.user.surname %></td>
        <td>
<%if  current_user.id == bid.hit.user_id%>
     <% if bid.active == true%>
           <%if bid.accept == true%>
           <h2>Εχετε δεχτεί την προσφορά!</h2>
           <%else%>
          <%= link_to 'Αποδοχή', accept_bid_path(bid), :method => 'put', :confirm => 'Είστε σίγουρος για την αποδοχή της προσφοράς;Μέτα την αποδοχή της προσφοράς οι υπολοιπες προσφορές για την αγγελεία θα απενεργοποιηθούν' ,:class => 'btn btn-success' %>
          <%end%>
      <%else %>
          Ανενεργή
         </td>
      </tr>
<%end%>
<% end %>
<%end%>
  </tbody>
</table>

<%= paginate @bids %>
</br>
  <%= link_to 'Πίσω', url_for(:back), :class => 'btn'  %>
<%if @hit.bids.exists?(:user_id => current_user.id)%>
Έχετε κάνει προσφορά για αυτή την αγγελία
<%else%>
<% if @hit.user_id != current_user.id %>
<%= link_to 'Κατάθεση προσφοράς', new_hit_bid_path(@hit), :class => 'btn btn-primary' %>
<%end%>
<%end%>
<%end%>

app/views/bids/mybids.html.erb
<% if @userbids  == 0 %>
<h1>Προσφορές</h1>
</br>
<h3>Δεν έχετε κάνει ακόμη προσφορές</h3>
</br>
<p>Για να κάνετε μια προσφορά πατήστε <%= link_to 'εδώ', hits_path, :class => 'btn btn-info' %> για να δείτε όλες τις διαθέσημες αγγελίες!</p>
</br>
</br>
<%else%>

</br>

<h1>Οι προσφορές μου</h1>

</br>
</br>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Κατάσταση</th>
      <th>Προσφορά</th>
      <th>Δημιουργήθηκε</th>
      <th>Αγγελία</th>
      <th>Ενέργειες</th>

    </tr>
  </thead>
  <tbody>
    <% @bids.each do |bid| %>
      <tr>
<%if bid.accept == true%>
        <td><img src="http://placehold.it/30x30" alt=""></td>
<%else%>
<td><img src="http://placehold.it/35x35" alt=""></td>
<%end%>
        <td><%= link_to bid.size, bid_path(bid) %></td>
        <td><%= time_ago_in_words(bid.created_at) %> ago</td>
        <td><%= link_to bid.hit.subject, hit_path(bid.hit) %></td>
        <td><%if bid.active == true%>
          <%= link_to 'Αλλαγή', edit_bid_path(bid), :class => 'btn btn-mini' %>
          <%= link_to 'Διαγραφή', bid_path(bid), :method => :delete,  :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
            <%else%>
            Ανενεργή
            <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @bids %>
<%end%>
  <%= link_to 'Πίσω', url_for(:back), :class => 'btn'  %>
</br>
</br>

app/views/bids/new.html.erb
<%if current_user.pro == true%>
<%if current_user.id == @bid.hit.user_id%>
</br>
</br>
</br>
<h3>Η αγγελία για την οποία ζητήσατε να κάνετε προσφορά έχει καταχωρηθεί από εσας και ως εκ τούτου δεν μπορείτε να καταχωρησετε προσφορά.</h3>
</br></br>
<a> <%= link_to 'Πίσω', url_for(:back), :class => 'btn btn-primary btn-large' %></a>
</br></br></br></br></br></br></br></br></br>
<%else%>
<%= render :partial => 'form' %>
<%end%>
<%else%>
</br></br></br>
Δεν έχετε το δικαίωμα να κάνετε προσφορές.Για να μπορείτε να κάνετε προσφορές αναβαθμίστε τον λογαριασμό σας και λάβετε δικαιώματα pro για ένα μήνα δωρεάν!
</br></br></br></br></br></br></br></br></br>
<%end%>

app/views/bids/show.html.erb
<h1>Προσφορά</h1>
</br>
<p>
  <b>Μέγεθος προσφοράς</b><br>
  <%= @bid.size %>
</p>

<p>
  <b>Για την αγγελία</b><br>
  <%= @bid.hit.subject %>
</p>

<p>
  <b>Το μήνυμά σας</b><br>
  <%= @bid.pm %>
</p>
<div class="form-actions">
<%if @bid.accept == true%>
<p>
Η προσφορά έχει γίνει δεκτή!</br>
Στοιχεία επικοιωνίας με τον πελάτη:
<%=@bid.hit.user.email%>
</p>
<%else if @bid.active == false%>
Η προσφορά είναι ανενεργή
<%else%>Δεν υπάρχουν νέα για την προσφορά
<%end%>
<%end%>
</div>

<div class="form-actions">
  <%= link_to 'Πίσω', url_for(:back), :class => 'btn'  %>
<%if @bid.accept == true%>
Η αγγελεία έχει γίνει δεκτή και δεν μπορείτε πλέον να την επεξεργαστείτε η να την διαγράψετε.
<%else%>
<%if @bid.user_id == current_user.id %>
<%if @bid.active == true%>
  <%= link_to 'Επεξεργασία', edit_bid_path(@bid), :class => 'btn' %>
  <%= link_to 'Διαγραφή', bid_path(@bid), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-danger' %>
<%else%>
Η προσφορά αυτή είναι <u>Ανενεργή</u>
<%end%>
<%end%>
<%end%>
</div>