config/routes.rb
Tweb::Application.routes.draw do

  resources :prefectures

  resources :nomos

  match  "/search" => "hits#search"
  match  "/myhits" => "hits#myhits"
  match  "/mybids" => "bids#mybids"
  resources :hits do
  resources :bids
end

resources :bids do
  put :accept, :on => :member
  put :inactive, :on => :member
end

get 'bids/accept'

  resources :categories
  devise_for :users

  resources :hits

  get "home/index"

namespace 'chargify' do
 match '/hooks' => "hooks#dispatch_handler", :via => "post"
 end

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post

   root :to => 'home#index'

end

app/models/hit.rb
class Hit < ActiveRecord::Base
  attr_accessible :hit_id, :body, :subject, :user_id, :category_id, :image, :bidmax, :bidmin, :prefecture_id
  validates :subject, :presence => true, :length => { :maximum => 50 }
  validates :body, :presence => true, :length => { :maximum => 200 }
  validates :category_id, :presence => true
     paginates_per 15
has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },:default_url => "/:class/:attachment/missing_:style.jpeg"
belongs_to :user
belongs_to :category
belongs_to :prefecture
has_many :bids  ,:dependent => :destroy

end

app/controllers/hits_controller.rb
class HitsController < ApplicationController
before_filter :authenticate_user!

  # GET /hits
  # GET /hits.json
  def index
    @search = Hit.search(params[:search])
    @hits = @search.page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hits }
    end
  end

 def search
   @asearch = Hit.search(params[:search])
    @hits = @asearch.page(params[:page])
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @hits }
    end
  end



  def myhits
    @mysearch = Hit.where("user_id = ?", current_user.id).search(params[:search])
    @hits = @mysearch.page(params[:page])
    respond_to do |format|
      format.html # myhits.html.erb
      format.json { render json: @hits }
    end
  end


  # GET /hits/1
  # GET /hits/1.json
  def show
    @hit = Hit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @hit }
    end
  end

  # GET /hits/new
  # GET /hits/new.json
  def new
    @hit = Hit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @hit }
    end
  end

  # GET /hits/1/edit
  def edit
    @hit = Hit.find(params[:id])
  end

  # POST /hits
  # POST /hits.json
  def create
    @hit = Hit.new(params[:hit])

    respond_to do |format|
      if @hit.save
        format.html { redirect_to @hit, notice: 'Hit was successfully created.' }
        format.json { render json: @hit, status: :created, location: @hit }
      else
        format.html { render action: "new" }
        format.json { render json: @hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /hits/1
  # PUT /hits/1.json
  def update
    @hit = Hit.find(params[:id])

    respond_to do |format|
      if @hit.update_attributes(params[:hit])
        format.html { redirect_to @hit, notice: 'Hit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @hit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /hits/1
  # DELETE /hits/1.json
  def destroy
    @hit = Hit.find(params[:id])
    @hit.destroy

    respond_to do |format|
      format.html { redirect_to '/myhits',notice: 'Hit was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/hits_helper.rb
module HitsHelper
end

app/views/hits/_form.html.erb
<%= simple_form_for @hit, :html => { :class => 'form-horizontal' } do |f| %>

<ul>
    <% @hit.errors.full_messages.each do |msg| %>
<div class="alert alert-error">
      <%= msg %>
</div>
    <% end %>
    </ul>

  <fieldset>
    <legend>Δημιουργία Αγγελίας</legend>
    <div class="control-group">
      <%= f.label :Περιγραφή, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_field :subject, :class => 'text_field',:placeholder => 'Σύντομη περιγραφή αγγελίας.'	 %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :Αναλυτική_περιγραφή, :class => 'control-label' %>
      <div class="controls">
        <%= f.text_area :body, :class => 'input-large',:placeholder => 'Αναλυτική περιγραφή αγγελίας.' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :Χαμηλότερη_δεκτή_προσφορά, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :bidmin, :class => 'text_area',:placeholder => 'Αναλυτική περιγραφή αγγελίας.' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :Υψηλότερη_δεκτή_προσφορά, :class => 'control-label' %>
      <div class="controls">
        <%= f.number_field :bidmax, :class => 'text_area',:placeholder => 'Αναλυτική περιγραφή αγγελίας.' %>
      </div>
    </div>
    <div class="control-group">
      <%= f.label :Βοηθητική_φωτογραφία, :class => 'control-label' %>
      <div class="controls">
    <%= f.file_field :image %>
<p class="help-block">* Η φωτογραφία μπορει να βοηθήσει στην καλυτερη αξιολόγηση της αγγελίας και έτσι καλύτερη προσφορά.</p>
    </div>
    </div>
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <div class="control-group">
      <%= f.label :Κατηγορία, :class => 'control-label' %>
        <%= f.association :category, :label => false %>
      </div>
    <div class="control-group">
      <%= f.label :Νομός, :class => 'control-label' %>
        <%= f.association :prefecture, :label => false %>
      </div>
    <div class="form-actions">
      <%= f.submit 'Δημοσιέυση αγγελίας ', :class => 'btn btn-primary' %>
      <%= link_to 'Άκυρο', hits_path, :class => 'btn' %>
    </div>
  </fieldset>
<% end %>

app/views/hits/edit.html.erb
<%if @hit.user_id == current_user.id%>
<%= render :partial => 'form' %>
<%else%>
Για να κάνετε επεξεργασία μιας αγγελίας θα πρέπει να είστε και ο κάτοχός της ;)
<%end%>

app/views/hits/index.html.erb
<h1>Αγγελίες</h1>
</br>
<%if @hits.count == 0%>
Λυπούμαστε αλλά δεν υπάρχουν αγγελίες με τα κριτήρια που δώσατε,ξαναδοκιμάστε πατώντας   <%= link_to 'εδώ', url_for(:back), :class => 'btn'  %>
</br></br></br></br></br></br></br></br></br></br></br>

<%else%>
<%=form_for @search do |f|%>
<%= f.label :subject_contains, 'Αναζήτηση βάση κατηγορίας' %>
<%= f.collection_select :category_id_equals, Category.all, :id, :name, :include_blank => 'Όλες' %>
<%= f.label :subject_contains, 'Αναζήτηση βάση νομού' %>
<%= f.collection_select :prefecture_id_equals, Prefecture.all, :id, :name, :include_blank => 'Όλοι' %>
<%= f.submit "Αναζήτηση", :class => 'btn-success' %>
<%end%>

<p>
Ταξινόμηση κατά:
<%= sort_link @search, :updated_at,"Πρόσφατα ενημερωμένες"%>|
<%= sort_link @search, :created_at,"Καινούριες"%>|
<%= sort_link @search, :bidmax,"Μέγιστη προσφορά"%>
</p>
</br>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Περιγραφή</th>
      <th>Κατηγορία</th>
      <th>Ελάχιστη/Μέγιστη προσφορά</th>
      <th>Προσφορές</th>
      <th>Δημιουργήθηκε</th>
      <th>Ενέργειες</th>
    </tr>
  </thead>
  <tbody>
    <% @hits.each do |hit| %>
      <tr>
        <td><%= link_to hit.subject, hit_path(hit) %></td>
        <td><%= hit.category.name %></td>
        <td><%= hit.bidmin %> εώς <%=hit.bidmax%></td>
        <td><%= link_to hit.bids.count, hit_bids_path(hit) %></td>
        <td><%= time_ago_in_words(hit.created_at) %></td>
        <td>
          <% if hit.user == current_user%>
           <%= link_to 'Επεξεργασία', edit_hit_path(hit), :class => 'btn btn-mini' %>
           <%= link_to 'Διαγραφή', hit_path(hit), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
         <%else%>
            <%if hit.bids.exists?(:user_id => current_user.id)%>
              Έχετε κάνει ήδη προφορά!
           <%else%>
           <%if hit.haveaccept == true%>
             Έχει ήδη αποδεχθεί προσφορά
           <%else%>
          <%= link_to 'Χτύπα το!', new_hit_bid_path(hit), :method => :get , :class => 'btn btn-success' %>
         <%end%>
         <%end%>
         <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @hits %>

    <% end %>

app/views/hits/myhits.html.erb
<% if @hits.count  == 0 %>
<h1>Οι αγγελίες μου</h1>
</br>
<h3>Δεν έχετε καταχωρημένες αγγελίες</h3>
</br>
<p>Για να καταχωρήσετε μια αγγελία πατήστε <%= link_to 'εδώ', new_hit_path, :class => 'btn btn-info' %> για να μεταφερθείτε στην σελίδα καταχώρησης αγγελίας</p>
</br>
</br>
</br>
</br>
</br>
</br>
<%else%>
<h1>Οι αγγελίες μου</h1>
</br>


<table class="table table-striped">
  <thead>
    <tr>
      <th>Περιγραφή</th>
      <th>Κατηγορία αγγελίας</th>
      <th>Δημιουργήθηκε</th>
      <th>Τελευταία ανενέωση</th>
      <th>Προσφορές αγγελίας</th>
      <th>Ενέργειες</th>


    </tr>
  </thead>
  <tbody>
    <% @hits.each do |hit| %>
      <tr>
        <td><%= link_to hit.subject, hit_path(hit) %></td>
        <td><%= hit.category.name %></td>
        <td><%= hit.created_at %></td>
        <td><%= time_ago_in_words(hit.updated_at)%></td>
        <td><%= link_to hit.bids.count, hit_bids_path(hit) %></td>
        <td>
            <% if hit.user == current_user%>
           <%= link_to 'Επεξεργασία', edit_hit_path(hit), :class => 'btn btn-mini' %>
           <%= link_to 'Διαγραφή', hit_path(hit), :method => :delete, :confirm => 'Are you sure?', :class => 'btn btn-mini btn-danger' %>
         <%else%>
          <%= link_to 'Χτύπα το!', new_hit_bid_path(hit), :method => :get , :class => 'btn btn-success' %>
         <%end%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%end%>
</br>
</br>

app/views/hits/new.html.erb
<%= render :partial => 'form' %>

app/views/hits/search.html.erb
<h3>Αναζήτηση αγγελιών</h3></br>

<%=form_for @asearch do |f|%>
<%= f.label :subject_contains, 'Να περιέχει στο θέμα' %>
<%= f.text_field :subject_contains %>
<%= f.label :subject_contains,'Με ημερομηνία υποβολής μετά από' %>
<%= f.datetime_select :created_at_greater_than %>
  <p>
    <%= f.label :bidmax_gte, "Price ranges from" %>
    <%= f.text_field :bidmax_gte, :size => 8 %>
    <%= f.label :bidmax_lte, "to" %>
    <%= f.text_field :bidmax_lte, :size => 8 %>
  </p>
<%= f.label :subject_contains, 'Κατηγορία' %>
<%= f.collection_select :category_id_equals, Category.all, :id, :name, :include_blank => true %>
</br>
<%= f.submit "Αναζήτηση", :class => 'btn btn-success' %>
<%end%>

app/views/hits/show.html.erb
</br>
<h1>  <%= @hit.subject %>	</h1>
</br>
</br>



<p>
  <b>Θέμα</b><br>
  <%= @hit.body %>
</p>
</br>
<p>
  <b>Εικόνα</b><br>
   <td><%= image_tag @hit.image.url(:medium) %></td>
</p>
</br>
<p>
  <b>Χρήστης</b><br>

  <%= @hit.user.name %>
</p>

<p>
  <b>Κατηγορία</b><br>
  <%= @hit.category.name %>
</p>


<p>
  <b>Σύνολο Προσφορών </b><span class="badge badge-inverse">
  <%= link_to @hit.bids.count, hit_bids_path(@hit) %>
</span>
</p>
<%if current_user.id == @hit.user_id%>
<%if @hit.haveaccept == true%>
   Έχετε ήδη αποδεχθεί προσφορά για αυτή την αγγελία
<%end%>
<%else%>
<%if @hit.haveaccept == true%>
  Ο χρήστης της αγγελίας έχει ήδη αποδεχθεί μια προσφορά
<%end%>
<%end%>
<div class="form-actions">
<%if @hit.bids.count != 0 %>
  <%= link_to "Δείτε τις προσφορές",hit_bids_path(@hit), :method => :get , :class => 'btn btn-success' %>
<%else%>
<%if @hit.user_id == current_user.id%>
<a><h3>Hit!</h3>Εαν για πολύ καιρό δεν υπάρχουν προσφορές βελτιώστε το θέμα και το περιεχόμενο της αγγελίας..  </a>
<%end%>
<%end%>
<%if @hit.bids.exists?(:user_id => current_user.id)%>
Έχετε κάνει ήδη προσφορά για αυτή την αγγελία
<%else%>
<%if @hit.user_id != current_user.id%>
<%if current_user.pro == true%>
<%if @hit.haveaccept == false%>
  <%= link_to "Κάντε μια προσφορά!",new_hit_bid_path(@hit), :method => :get , :class => 'btn btn-success' %>
<%end%>
<%end%>
<%end%>
<%end%>
</div>
<%if @hit.user_id == current_user.id%>
<div class="form-actions">
  <%= link_to 'Back', hits_path, :class => 'btn'  %>
  <%= link_to 'Edit', edit_hit_path(@hit), :class => 'btn' %>
  <%= link_to 'Delete', hit_path(@hit), :method => 'delete', :confirm => 'Είστε σίγουρος?', :class => 'btn btn-danger' %>
</div>
<%end%>