config/routes.rb
Tweb::Application.routes.draw do

  resources :prefectures

  resources :nomos

  match  "/search" => "hits#search"
  match  "/myhits" => "hits#myhits"
  match  "/mybids" => "bids#mybids"
  resources :hits do
  resources :bids
end

resources :bids do
  put :accept, :on => :member
  put :inactive, :on => :member
end

get 'bids/accept'

  resources :categories
  devise_for :users

  resources :hits

  get "home/index"

namespace 'chargify' do
 match '/hooks' => "hooks#dispatch_handler", :via => "post"
 end

match 'contact' => 'contact#new', :as => 'contact', :via => :get
match 'contact' => 'contact#create', :as => 'contact', :via => :post

   root :to => 'home#index'

end

app/models/prefecture.rb
class Prefecture < ActiveRecord::Base
has_many :hits
end

app/controllers/prefectures_controller.rb
class PrefecturesController < ApplicationController
  # GET /prefectures
  # GET /prefectures.json
  def index
    @prefectures = Prefecture.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @prefectures }
    end
  end

  # GET /prefectures/1
  # GET /prefectures/1.json
  def show
    @prefecture = Prefecture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @prefecture }
    end
  end

  # GET /prefectures/new
  # GET /prefectures/new.json
  def new
    @prefecture = Prefecture.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @prefecture }
    end
  end

  # GET /prefectures/1/edit
  def edit
    @prefecture = Prefecture.find(params[:id])
  end

  # POST /prefectures
  # POST /prefectures.json
  def create
    @prefecture = Prefecture.new(params[:prefecture])

    respond_to do |format|
      if @prefecture.save
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully created.' }
        format.json { render json: @prefecture, status: :created, location: @prefecture }
      else
        format.html { render action: "new" }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /prefectures/1
  # PUT /prefectures/1.json
  def update
    @prefecture = Prefecture.find(params[:id])

    respond_to do |format|
      if @prefecture.update_attributes(params[:prefecture])
        format.html { redirect_to @prefecture, notice: 'Prefecture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @prefecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prefectures/1
  # DELETE /prefectures/1.json
  def destroy
    @prefecture = Prefecture.find(params[:id])
    @prefecture.destroy

    respond_to do |format|
      format.html { redirect_to prefectures_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/prefectures_helper.rb
module PrefecturesHelper
end

app/views/prefectures/_form.html.erb
<%= simple_form_for(@prefecture) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/prefectures/edit.html.erb
<h1>Editing prefecture</h1>

<%= render 'form' %>

<%= link_to 'Show', @prefecture %> |
<%= link_to 'Back', prefectures_path %>

app/views/prefectures/index.html.erb
<h1>Listing prefectures</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @prefectures.each do |prefecture| %>
  <tr>
    <td><%= prefecture.name %></td>
    <td><%= link_to 'Show', prefecture %></td>
    <td><%= link_to 'Edit', edit_prefecture_path(prefecture) %></td>
    <td><%= link_to 'Destroy', prefecture, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Prefecture', new_prefecture_path %>

app/views/prefectures/new.html.erb
<h1>New prefecture</h1>

<%= render 'form' %>

<%= link_to 'Back', prefectures_path %>

app/views/prefectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @prefecture.name %>
</p>


<%= link_to 'Edit', edit_prefecture_path(@prefecture) %> |
<%= link_to 'Back', prefectures_path %>